print_info() {
    prin "          ╭────────────────────────────────╮"
    info "          OS  " distro
    info "          ker " kernel
    info "          cpu " cpu
    info "          ram " memory
    prin "          ╰────────────────────────────────╯"
}
gap=8
colors=(7 7 7 1 1 7)
bold="off"
underline_enabled="on"
underline_char="━"
separator="      "
color_blocks="off"
uptime_shorthand="off"
memory_percent="off"
package_managers="off"
cpu_cores="off"
cpu_brand="off"
distro_shorthand="on"
os_arch="off"
cpu_speed="off"
ascii_distro="arch_small"
ascii_colors=(7)
ascii_bold="on"
