
exec-once = waybar
exec-once = dunst
exec-once = ~/.config/hypr/proton.sh
exec-once = ~/.config/hypr/spotify.sh

monitor=VGA-1,1280x720@60,0x0,1

$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun

input {
    kb_layout = br
    follow_mouse = 1
    repeat_rate = 50
    repeat_delay = 200
    sensitivity = 0
    accel_profile = flat
    force_no_accel = true
    touchpad {
        disable_while_typing = false
    }
}

general {
    gaps_in = 1
    gaps_out = 1
    border_size = 2
}

decoration {
    blur {
        enabled = false
    }
}

animations {
    enabled = yes
    bezier = ultraCremoso, 0.16, 1, 0.3, 1
    bezier = slowFlow, 0.2, 0.9, 0.1, 1
    animation = windows, 1, 7, slowFlow, popin 0%
    animation = windowsMove, 1, 7, ultraCremoso
    animation = fade, 1, 10, default
    animation = workspaces, 1, 10, ultraCremoso, slidefade 20%
}

misc {
    disable_hyprland_logo = true
    force_default_wallpaper = 0
}

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exit,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, W, exec, firefox
bind = $mainMod, R, exec, $menu
bind = $mainMod, F1, exec, ~/.config/hypr/switch_theme.sh
bind = $mainMod, X, exec, ~/.config/hypr/powermenu.sh
bind = $mainMod, B, exec, pkill waybar && waybar
bind = $mainMod, V, togglefloating,
bind = $mainMod, L, exec, hyprlock
bind = , F11, fullscreen

bind = , Print, exec, mkdir -p ~/prints && grim ~/prints/print$(ls ~/prints | wc -l).png && notify-send "Captura" "Salva"

bind = ALT, Q, exec, gpu-screen-recorder -w screen -f 60 -c mp4 -r 120 -a default_output -o ~/Videos && notify-send "Replay" "ON"
bind = ALT, E, exec, killall -SIGINT gpu-screen-recorder && notify-send "Replay" "OFF"
bind = ALT, S, exec, killall -SIGUSR1 gpu-screen-recorder && notify-send "Replay" "SAVED"

bind = $mainMod, N, exec, pgrep hyprsunset && killall hyprsunset || hyprsunset --temperature 2000

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
